### ISSUE TITLE
AUC score of 0.5 on Assistment data

### ISSUE THREAD

**Issue by luffycodes** [dxywill/deepknowledgetracing#1]
Hey,

I tried running the code on Assistment data. However, even after 5-6 epochs, the AUC comes around 0.52.

Please let me know if we need to adjust certain things to get the score of 0.82 as in the stanford paper.

Thanks in advance :)

**Comment by dxywill** [comment]
5-6 epochs is far from enough, it usually takes ~60 epochs to converge

**Comment by luffycodes** [comment]
hey,

thanks for the prompt reply :)

i just ran for > 100 epochs, however the accuracy does not go above 0.58

**Comment by luffycodes** [comment]
Using RMSprop with dropout=0.0 instead of Adam really helped to increase the test AUC to 0.78 and training to around 0.9 after ~60 epochs.

Edit : Awesomely written code man ! Thanks a ton..
