### ISSUE TITLE
test accuary is below the paper's result

### ISSUE THREAD

**Issue by Nullees** [dxywill/deepknowledgetracing#2]
![image](https://user-images.githubusercontent.com/24388879/70890557-51b3c680-2020-11ea-8183-f8076f912bb2.png)
This is my tensorboard image of test acc.But it's always below the paper's result.
The params are all same with your.
Please give some advice for me. Thanks

**Comment by dxywill** [comment]
Hi Nullees,

The Assistment 09-10 dataset the original DKT paper used has duplication which highly inflated the performance of this model.  
Xiong et al. created their own version with duplicated records removed. [http://www.educationaldatamining.org/EDM2016/proceedings/paper_133.pdf](http://www.educationaldatamining.org/EDM2016/proceedings/paper_133.pdf). They reported the highest auc is around 0.80. I think this is an reasonable results. However, it is possible to get -+ 0.2 results based on actual implementation like the language you use (pytorch, tensorflow), your running machine (this may impact the the initialization for the parameters). 
For those papers who claim they could achieve > 0.85 results, I choose not to believe them unless they publish their code.

**Comment by dxywill** [comment]
@Nullees  forget to mention, the 0.80 auc is for the assistment 09-10 (a) dataset from Xiong's paper, if you use them together, I believe the results is around 0.75.  See this paper also [https://link.springer.com/article/10.1007/s12559-017-9522-0](https://link.springer.com/article/10.1007/s12559-017-9522-0)

**Comment by Nullees** [comment]
@dxywill Thanks very much! 
Now I’m puzzled about the AUC result of Bidirection-LSTM.I have try change the LSTM to Bi-LSTM by pytorch API (only change "Bidirctional=True" and "hidden_size*2" as follow pictures).But AUC improved to **0.99**!! I don't believe this result,but i can't explain this clearly. Could you give me some advice??Thanks
![image](https://user-images.githubusercontent.com/24388879/71151734-6df97280-226f-11ea-905d-5fd320ed267f.png)
![image](https://user-images.githubusercontent.com/24388879/71151742-794c9e00-226f-11ea-835f-120246e3de9c.png)
![image](https://user-images.githubusercontent.com/24388879/71151810-a39e5b80-226f-11ea-90b0-e5de23a818fa.png)

**Comment by dxywill** [comment]
Hi @Nullees ,

If you see AUC close to 1, I would check if you are including testing data in your training set, especially you are using Bi-directional LSTM.

**Comment by Nullees** [comment]
Ok thanks. but at fact, i don't know where cause to this unbelievable AUC result. Because i just change the LSTM function's arguments(**Bidirectional=True** and **hidden_size * 2**). So, what else can i do in next step?
